[project]
name = "agentic-ai-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shahab-khan396", email = "ksab2922@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "openai>=3.13.0",
    "pageindex>=0.2.8",
    "python-dotenv>=1.2.3",
]

[project.scripts]
agentic-ai-practice = "agentic_ai_practice:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
